# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('0', 'DNI'), ('1', 'Pasaporte'), ('2', 'Carnet de Extranjeria'), ('3', 'Carnet Universitario')], max_length=1)),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona'},
        ),
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='wasd@sadas.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
