# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170624_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento'},
        ),
    ]
